name: Sysdig Pipeline Scan

# Prerequisites:
# - Create a GitHub Action secret for SECURE_API_TOKEN with your own API Token

on:
  # Uncomment this for a manual trigger in GitHub Workflow
  workflow_dispatch:

  # Set the CronJob to run the scanner periodically
  # schedule:
  #   - cron: '0 0 * * *' # Runs at midnight (0:00 AM) every day

env:
  # Set SYSDIG_URL based on your Sysdig SaaS Region
  # Reference: https://docs.sysdig.com/en/docs/administration/saas-regions-and-ip-ranges/
  SYSDIG_URL: https://app.au1.sysdig.com

  #Set BYPASS_SCAN_FAIL to true if you want to forcibly pass the pipeline scan result
  BYPASS_SCAN_FAIL: false
  
jobs:
  scan_images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Sysdig CLI Scanner
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner
        
    - name: Scan images
      run: |
        # Define your image names here:
        images=("nginx:1.27.2-alpine" "busybox:1.35.0")
        for image in "${images[@]}"
        do
          SECURE_API_TOKEN=${{ secrets.SECURE_API_TOKEN }} ./sysdig-cli-scanner --apiurl ${{env.SYSDIG_URL}} "$image" || ${{ env.BYPASS_SCAN_FAIL }}
        done
